services:
  redis:
    image: redis
    volumes:
      - ./counter/data:/data
  counter:
    image: nagaevvs/lib-counter:0.2
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis
    depends_on:
      - redis
  server:
    image: nagaevvs/lib-server:0.2
    ports:
      - 80:5000
    environment:
      - PORT=5000
    